print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/swanijam/Documents/_Game_Dev/BleeborpMountains/BleeborpMountains/Assets/Models/obstacles/duck.ma"`)
{		
	file -o "/Users/swanijam/Documents/_Game_Dev/BleeborpMountains/BleeborpMountains/Assets/Models/obstacles/duck.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/swanijam/Documents/_Game_Dev/BleeborpMountains/BleeborpMountains/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/swanijam/Documents/_Game_Dev/BleeborpMountains/BleeborpMountains/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/swanijam/Documents/_Game_Dev/BleeborpMountains/BleeborpMountains/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
